### ISSUE TITLE
Openlca2bw version 0.0.0 on PyPi

### ISSUE THREAD

**Issue by alyabolowich** [cyrillefrancois/openlca2bw#8]
Hello,

I am trying to install openlca2bw==1.0.0, and I get an error if I specify this version.

Attempt: 

> `pip install openlca2bw==1.0.0`

Error message: 

> `ERROR: Could not find a version that satisfies the requirement openlca2bw==1.0.0 (from versions: 0.0.0, 0.2.2.post0.dev0)`
> `ERROR: No matching distribution found for openlca2bw==1.0.0`

Running `pip install openlca2bw` installs the version 0.0.0 (see [https://pypi.org/project/openlca2bw/](https://pypi.org/project/openlca2bw/)). 

I am able to install the previous version (`pip install openlca2bw==0.2.2.post0.dev0` or via `pip install git+https://github.com/cyrillefrancois/openlca2bw`).

Any idea why we cannot install v1.1.0 or v1.0.0? 

Thank you!

**Comment by cyrillefrancois** [comment]
I pip there is no V1.0.0
I did not create the pip release properly. So versions are not well-defined.
But if you use `pip install openlca2bw ` it should work. (with python 3.9 at least)
The last version is 0.0.0
The previous one (with multiple errors) is 0.2.2.post0.dev0

**Comment by cyrillefrancois** [comment]
The last version is now 1.0.0. Normally, I have deactivated previous pip versions
