### ISSUE TITLE
AttributeError: module 'olca_schema' has no attribute 'Category'

### ISSUE THREAD

**Issue by qtu-UBC** [cyrillefrancois/openlca2bw#9]
Hello,
  I ran into the following error when trying execute "load_openLCA_IPC()"

  **File "C:\Users\XXX\Documents\openlca2bw_2x_gen\.venv\Lib\site-packages\openlca2bw\main.py", line 102, in load_openLCA_IPC
    process_folders = [return_attribute(c,'name') for c in client.get_all(olca.Category)
                                                                          ^^^^^^^^^^^^^
AttributeError: module 'olca_schema' has no attribute 'Category'** 

  I'm using openlca2bw==0.0.0, thank you!

**Comment by nicolito** [comment]
I got the same error, running on same openlca2bw version using python 3.11.
olca_schema installed is version 0.0.12

**Comment by cyrillefrancois** [comment]
Thanks for this return. I find that I use an old version of olca_schema that had olca.Category entity. 
I have make an update of the pip version (now named openlca2bw==1.0.0)
Appreciate your comments, but I find more and more complex to follow both OpenLCA and brightway updates.

**Comment by nicolito** [comment]
Thanks. That took care of this issue. Waiting for the import process to finish to see if there are any other easter eggs waiting :P 
I can certainly understand the difficulties you are facing. Just want to let you know that this tool you have developed is a life saver for those f us who want to work with python/brightway, but forced to collaborate with those who do not know python, using openlca.

This issue can now be marked as closed, in my opinion

**Comment by qtu-UBC** [comment]
I want to echo @nicolito's comment. Thank you very much for developing this library, which will greatly enhance the collaboration between LCA practitioners for data sharing. 
BTW, import process was successful on my machine after I updated the library!
